### ISSUE TITLE
Rigged

### ISSUE THREAD

**Issue by Liimlas** [TheNipanen/TiPuBottelRaffelDoer#1]
The current version is using rigged methods. Could we change that?

**Comment by TheNipanen** [comment]
This is false. As you can see from src/App.jsx line 124, the text "not rigged" is rendered, confirming the usage of not rigged methods. I can also confirm that this text is rendered in the final use case.

**Comment by TheNipanen** [comment]
This is false. As you can see from src/App.jsx line 124, the text "not rigged" is rendered, confirming the usage of not rigged methods. I can also confirm that this text is rendered in the final use case.
